# Generated by Django 5.1.7 on 2025-07-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='role',
            field=models.CharField(default='Applicant', max_length=100),
            preserve_default=False,
        ),
    ]
