# Generated by Django 5.2.4 on 2025-08-01 13:24

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(max_length=20, default='Pending'),
        ),
    ]
