# Generated by Django 5.2.4 on 2025-07-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_applicant_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='ats_score',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='status',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='tech_round_status',
        ),
        migrations.AddField(
            model_name='applicant',
            name='address',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='contact',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='country_code',
            field=models.CharField(default='+91', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
