# Generated by Django 5.1.7 on 2025-07-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='address',
            field=models.TextField(default='Applicant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='contact',
            field=models.CharField(default='Applicant', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='country_code',
            field=models.CharField(choices=[('+91', '+91 India'), ('+1', '+1 USA'), ('+44', '+44 UK'), ('+61', '+61 Australia'), ('+81', '+81 Japan')], default='+91', max_length=5),
        ),
    ]
