# Generated by Django 5.2.4 on 2025-07-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_applicant_ats_score_remove_applicant_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='country_code',
            field=models.CharField(choices=[('+91', '+91 India'), ('+1', '+1 USA'), ('+44', '+44 UK'), ('+61', '+61 Australia'), ('+81', '+81 Japan')], default='+91', max_length=5),
        ),
    ]
