# Generated by Django 5.2.4 on 2025-08-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_add_ats_and_tech_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='generated_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='joining_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='tech_round_status',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10),
        ),
    ]
