# Generated by Django 5.1.7 on 2025-07-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_notification_applicant_address_applicant_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='contact',
            field=models.CharField(max_length=100),
        ),
    ]
