# Generated by Django 5.2.4 on 2025-07-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_applicant_status_alter_applicant_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
    ]
