# Generated by Django 5.2.4 on 2025-07-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_applicant_ats_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='ats_score',
            field=models.FloatField(default=0.0),
        ),
    ]
