# Generated by Django 5.2.4 on 2025-07-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_visitor'),
        ('members', '0006_alter_applicant_ats_score'),
    ]

    operations = [
    ]
