# Generated by Django 5.2.4 on 2025-07-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_merge_0003_visitor_0006_alter_applicant_ats_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='country_code',
        ),
        migrations.AddField(
            model_name='applicant',
            name='tech_round_status',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], default='migration', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ats_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cover_letter',
            field=models.TextField(blank=True, default='Pending'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
