# Generated by Django 5.2.4 on 2025-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_notification_remove_applicant_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='ats_score',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='status',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='tech_round_status',
        ),
        migrations.AddField(
            model_name='applicant',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='contact',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='country_code',
            field=models.CharField(choices=[('+91', '+91 India'), ('+1', '+1 USA'), ('+44', '+44 UK'), ('+61', '+61 Australia'), ('+81', '+81 Japan')], default='+91', max_length=5),
        ),
        migrations.AddField(
            model_name='notification',
            name='ats_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='notification',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
