# Generated by Django 5.2.4 on 2025-07-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_applicant_ats_score_remove_applicant_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='ats_score',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
